version: '3'
services:

  tink-python-api-types:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: tink-http-python
    entrypoint: "poetry run pytest"
    tty: false
    working_dir: /app
    volumes:
      - ./:/app
